on: 
  repository_dispatch:
    types:
      - resource-published
      - resources-published
      - resource-unpublished
      - resources-unpublished
      - resource-previewed
      - resources-previewed
      - resource-unpreviewed
      - resources-unpreviewed
jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "Payload: $JSON"
        env:
          JSON: ${{ toJson(github.event.client_payload) }}
  log:
    runs-on: ubuntu-latest
    steps:
      - run: |
          curl -XPOST -vi \
            -H 'content-type: application/json' \
            -d "{ \"data\": { \"type\": \"${{ github.event.action }}\", \"payload\": \"${{ JSON }}\" } }" \
            'https://main--public-test--maxakuru.hlx.live/tools/event-log'
        env:
          JSON: ${{ toJson(github.event.client_payload) }}
